"""Tests for the LLM-based narrative and translation layer (M3 Phase 3)."""

from unittest.mock import MagicMock, patch

import pytest

from agents.agent_b_analysis.llm_layer import SafetyCardNarrator
from agents.protocols.schemas import (
    ProvenancedThreshold,
    SafetyEvaluationResult,
    SafetyState,
    ThresholdDirection,
)


@pytest.fixture
def sample_result():
    return SafetyEvaluationResult(
        state=SafetyState.WARNING,
        chemical_name="Toluene",
        zone_id="Zone B",
        metric_name="max_storage_temperature",
        current_value=31.0,
        threshold_value=25.0,
        unit="C",
        provenance=ProvenancedThreshold(
            metric_name="max_storage_temperature",
            value=25.0,
            unit="C",
            direction=ThresholdDirection.MAX,
            sds_id="SDS-TOL-ABC-2026",
            supplier_name="ABC Chemicals",
            section_number="Section 7",
            authority_score=1.0,
            citation="ABC Chemicals Toluene SDS, 2026-02, Section 7, Page 5"
        ),
        reasoning="Observed temperature 31.0 C exceeds maximum threshold of 25.0 C."
    )


def test_narrator_fallback_on_missing_key(sample_result):
    """Verifies that the narrator falls back gracefully when no API key is set."""
    narrator = SafetyCardNarrator(api_key=None)
    explanation = narrator.explain_alert(sample_result)
    assert "FALLBACK: The safety state is WARNING" in explanation
    assert sample_result.reasoning in explanation

    translated = narrator.translate_safety_card(sample_result, language="si")
    assert translated["chemical_name"] == "Toluene"
    assert translated["state"] == "WARNING"
    assert "[Translation Unavailable]" in translated["reasoning"]


@patch("agents.agent_b_analysis.llm_layer.Mistral")
def test_narrator_explain_alert_success(mock_mistral_class, sample_result):
    """Verifies successful alert explanation using Mistral."""
    mock_client = MagicMock()
    mock_mistral_class.return_value = mock_client
    
    mock_choice = MagicMock()
    mock_choice.message.content = "Test explanation generated by LLM."
    mock_client.chat.complete.return_value.choices = [mock_choice]

    narrator = SafetyCardNarrator(api_key="fake-key")
    explanation = narrator.explain_alert(sample_result)
    
    assert explanation == "Test explanation generated by LLM."
    mock_client.chat.complete.assert_called_once()


@patch("agents.agent_b_analysis.llm_layer.Mistral")
def test_narrator_translate_safety_card_success(mock_mistral_class, sample_result):
    """Verifies successful JSON translation return."""
    mock_client = MagicMock()
    mock_mistral_class.return_value = mock_client
    
    mock_choice = MagicMock()
    mock_choice.message.content = '{"chemical_name": "Toluene", "state": "WARNING", "reasoning": "Translated text", "citation": "Translated citation"}'
    mock_client.chat.complete.return_value.choices = [mock_choice]

    narrator = SafetyCardNarrator(api_key="fake-key")
    translated = narrator.translate_safety_card(sample_result, language="si")
    
    assert translated["chemical_name"] == "Toluene"
    assert translated["state"] == "WARNING"
    assert translated["reasoning"] == "Translated text"
    assert translated["citation"] == "Translated citation"
