"""ChemSentry API models — Pydantic schemas for requests/responses (M4).

Defines the contract between frontend, API gateway, and backend agents.
"""

from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional
from datetime import datetime


# ============================================================================
# Authentication & Authorization
# ============================================================================

class TokenResponse(BaseModel):
    """JWT token returned after successful login."""
    access_token: str
    token_type: str = "bearer"
    expires_in: int  # seconds


class UserRole(str, Enum):
    """RBAC roles for sign-off workflow."""
    VIEWER = "viewer"  # Read-only access (safety monitor)
    ANALYST = "analyst"  # Can query, view evidence
    ADMIN = "admin"  # Can sign off on alerts


class UserLogin(BaseModel):
    """User login request."""
    username: str
    password: str


class UserInfo(BaseModel):
    """User info in JWT payload and responses."""
    user_id: str
    username: str
    role: UserRole


# ============================================================================
# Sensor & Environment Data
# ============================================================================

class SensorReading(BaseModel):
    """DHT22 sensor reading from ESP32."""
    zone_id: str
    temperature_celsius: float = Field(..., ge=-40, le=80)  # DHT22 range
    humidity_percent: float = Field(..., ge=0, le=100)
    timestamp: datetime
    device_id: str  # ESP32 MAC or name


class ZoneState(BaseModel):
    """Aggregated state of a zone (room, storage area, etc)."""
    zone_id: str
    last_reading: SensorReading
    is_excursion: bool  # True if outside safe bounds
    safety_state: str  # "SAFE", "WARNING", "UNKNOWN"
    last_alert_timestamp: Optional[datetime] = None


# ============================================================================
# Retrieval & Evidence (from Agent A + Agent B)
# ============================================================================

class RetrievedDocument(BaseModel):
    """SDS document retrieved by Agent A."""
    doc_id: str
    title: str
    cas_number: str
    retrieval_score: float  # TF-IDF cosine similarity
    retrieved_section: str  # The relevant excerpt


class SafetyThreshold(BaseModel):
    """Safety threshold extracted from SDS."""
    parameter: str  # e.g., "temperature_max", "humidity_max"
    value: float
    unit: str  # e.g., "°C", "%"
    source_doc_id: str
    version: str  # SDS version


class EvidenceReconciliation(BaseModel):
    """Evidence from Agent A + Agent B reconciliation."""
    query_chemical: str
    retrieved_docs: list[RetrievedDocument]
    thresholds: list[SafetyThreshold]
    conflicts: list[str] = []  # Jaccard conflict notes
    final_safety_state: str  # "SAFE", "WARNING", "UNKNOWN"


# ============================================================================
# Supervisor Dashboard & Sign-Off
# ============================================================================

class AlertSeverity(str, Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """Alert generated by Agent B (severity classifier)."""
    alert_id: str
    zone_id: str
    chemical_identified: str
    severity: AlertSeverity
    evidence: EvidenceReconciliation
    timestamp: datetime
    created_by_user: str  # Which analyst triggered the query


class SignOffDecision(BaseModel):
    """Human sign-off on an alert (required before any external notification)."""
    alert_id: str
    approved: bool  # True = approve alert, False = reject
    notes: str  # Why approved/rejected
    signed_by_user: str  # Which admin signed off
    timestamp: datetime


# ============================================================================
# API Request/Response Envelopes
# ============================================================================

class QueryRequest(BaseModel):
    """Frontend sends a query about a chemical/condition."""
    chemical_name: str
    zone_id: Optional[str] = None  # If querying a specific zone
    context: Optional[str] = None  # e.g., "storage", "use", "emergency"


class QueryResponse(BaseModel):
    """API returns evidence, thresholds, and safety state."""
    query_id: str
    query: QueryRequest
    evidence: EvidenceReconciliation
    created_alert: Optional[Alert] = None  # If severity warrants alert


class HealthCheck(BaseModel):
    """Basic health status."""
    status: str  # "ok", "degraded", "error"
    database: str  # "ok" or error msg
    mqtt_broker: str  # "ok" or error msg
    version: str


# ============================================================================
# Metadata & Audit
# ============================================================================

class AuditLog(BaseModel):
    """Audit trail for compliance."""
    action: str  # e.g., "query", "sign_off", "alert_sent"
    user_id: str
    timestamp: datetime
    resource: str  # What was acted on (alert_id, query_id, etc)
    details: dict  # Additional context
