"""ChemSentry API models — Pydantic schemas for requests/responses (M4).

Defines the contract between frontend, API gateway, and backend agents.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

# ============================================================================
# Authentication & Authorization
# ============================================================================


class TokenResponse(BaseModel):
    """JWT token returned after successful login."""

    access_token: str
    token_type: str = "bearer"
    expires_in: int  # seconds


class UserRole(str, Enum):
    """RBAC roles for sign-off workflow."""

    VIEWER = "viewer"  # Read-only access (safety monitor)
    ANALYST = "analyst"  # Can query, view evidence
    ADMIN = "admin"  # Can sign off on alerts


class UserLogin(BaseModel):
    """User login request."""

    username: str
    password: str


class UserInfo(BaseModel):
    """User info in JWT payload and responses."""

    user_id: str
    username: str
    role: UserRole


# ============================================================================
# Sensor & Environment Data
# ============================================================================


class SensorReading(BaseModel):
    """DHT22 sensor reading from ESP32."""

    zone_id: str
    temperature_celsius: float = Field(..., ge=-40, le=80)  # DHT22 range
    humidity_percent: float = Field(..., ge=0, le=100)
    timestamp: datetime
    device_id: str  # ESP32 MAC or name


class ZoneState(BaseModel):
    """Aggregated state of a zone (room, storage area, etc)."""

    zone_id: str
    last_reading: Optional[SensorReading] = None
    is_excursion: bool  # True if outside safe bounds
    safety_state: str  # "SAFE", "WARNING", "UNKNOWN"
    last_alert_timestamp: Optional[datetime] = None


class ChemicalCheckOut(BaseModel):
    """One (chemical, metric) evaluation behind a zone's aggregated state.

    Agent C's `EnvironmentalMonitor` (agents/agent_c_environment/monitor.py)
    checks every chemical in a zone against every monitored metric; `ZoneState`
    alone only carries the worst-case aggregate. The Live Environment UI needs
    the underlying per-chemical reasoning and citation too -- "cited back to
    the user" applies here exactly as it does to a /query result.
    """

    chemical_name: str
    metric_name: str
    state: str  # "SAFE", "WARNING", "UNKNOWN"
    current_value: float
    threshold_value: Optional[float] = None
    reasoning: str
    citation: Optional[str] = None


class ZoneStatusResponse(ZoneState):
    """`ZoneState` plus the zone's known chemical inventory and the
    per-chemical evidence behind its aggregated `safety_state` -- what
    `GET /zones` and `POST /zones/{zone_id}/telemetry` actually return.
    """

    chemicals: list[str]
    checks: list[ChemicalCheckOut]


# ============================================================================
# Retrieval & Evidence (from Agent A + Agent B)
# ============================================================================


class RetrievedDocument(BaseModel):
    """SDS document retrieved by Agent A."""

    doc_id: str
    title: str
    cas_number: str
    retrieval_score: float  # TF-IDF cosine similarity
    retrieved_section: str  # The relevant excerpt


class SafetyThreshold(BaseModel):
    """Safety threshold extracted from SDS."""

    parameter: str  # e.g., "temperature_max", "humidity_max"
    value: float
    unit: str  # e.g., "°C", "%"
    source_doc_id: str
    version: str  # SDS version


class EvidenceReconciliation(BaseModel):
    """Evidence from Agent A + Agent B reconciliation."""

    query_chemical: str
    retrieved_docs: list[RetrievedDocument]
    thresholds: list[SafetyThreshold]
    conflicts: list[str] = []  # Jaccard conflict notes
    final_safety_state: str  # "SAFE", "WARNING", "UNKNOWN"


# ============================================================================
# Supervisor Dashboard & Sign-Off
# ============================================================================


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """Alert generated by Agent B (severity classifier)."""

    alert_id: str
    zone_id: str
    chemical_identified: str
    severity: AlertSeverity
    evidence: EvidenceReconciliation
    timestamp: datetime
    created_by_user: str  # Which analyst triggered the query


class SignOffDecision(BaseModel):
    """Human sign-off on an alert (required before any external notification)."""

    alert_id: str
    approved: bool  # True = approve alert, False = reject
    notes: str  # Why approved/rejected
    signed_by_user: str  # Which admin signed off
    timestamp: datetime


# ============================================================================
# API Request/Response Envelopes
# ============================================================================


class QueryRequest(BaseModel):
    """Frontend sends a query about a chemical/condition."""

    chemical_name: str
    zone_id: Optional[str] = None  # If querying a specific zone
    context: Optional[str] = None  # e.g., "storage", "use", "emergency"


class QueryResponse(BaseModel):
    """API returns evidence, thresholds, and safety state."""

    query_id: str
    query: QueryRequest
    evidence: EvidenceReconciliation
    created_alert: Optional[Alert] = None  # If severity warrants alert


class HealthCheck(BaseModel):
    """Basic health status."""

    status: str  # "ok", "degraded", "error"
    database: str  # "ok" or error msg
    mqtt_broker: str  # "ok" or error msg
    version: str


# ============================================================================
# Metadata & Audit
# ============================================================================


class AuditLog(BaseModel):
    """Audit trail for compliance."""

    action: str  # e.g., "query", "sign_off", "alert_sent"
    user_id: str
    timestamp: datetime
    resource: str  # What was acted on (alert_id, query_id, etc)
    details: dict  # Additional context


# ============================================================================
# Agent B — Co-Storage & Narration Responses (M3)
# ============================================================================


class CoStorageRule(BaseModel):
    """One Apriori-discovered association rule, with its CAMEO compatibility status.

    Deliberately does not carry a 'safe'/'unsafe' field: Apriori discovers
    co-occurrence patterns; the CAMEO lookup decides whether that pattern is a
    known reactivity risk. The route that returns these is read-only evidence,
    not a safety verdict.
    """

    antecedents: list[str]
    consequents: list[str]
    support: float
    confidence: float
    lift: float
    incompatibility_status: str  # e.g. "REACTIVE: ..." or "COMPATIBLE: ..."


class CoStorageCheckResponse(BaseModel):
    """Response for GET /zones/{zone_id}/co-storage-check.

    Returns the chemicals in the zone and all Apriori-mined association rules
    cross-referenced against the CAMEO incompatibility matrix.
    """

    zone_id: str
    chemicals: list[str]
    rules: list[CoStorageRule]


class NarrateAlertResponse(BaseModel):
    """Response for POST /alerts/{alert_id}/narrate.

    The LLM explanation and optional translation of an already-decided alert.
    The 'safety_state' field is always the deterministic verdict from the
    stored AlertRecord -- never the LLM's rephrasing of it -- so a
    mistranslation can never change what the caller reads as the verdict.
    """

    alert_id: str
    safety_state: str  # copied verbatim from AlertRecord.status context
    explanation: str
    translation: Optional[dict[str, str]] = None  # present only if language= supplied


# ============================================================================
# Agent B — Hazard Severity Classifier (M3, PR 2)
# ============================================================================


class SeverityRequest(BaseModel):
    """Request body for POST /classifier/severity.

    The three NFPA fields are explicitly required from the caller -- they are NOT
    extracted anywhere in this codebase (confirmed: no SDS in corpus/raw/ carries
    NFPA 704 diamond ratings, and extraction/value_extractor.py has no NFPA parser).
    Making them required rather than defaulting to 0 ensures the gap is visible at
    the API surface: a caller who doesn't know the NFPA ratings will get a 422
    validation error and will not receive a severity label silently computed from
    fabricated zeros.

    ghs_code_count can be derived from len(ProvenancedThreshold.hazard_statements)
    on any threshold retrieved by /query or /safety/evaluate -- that is the one
    feature this pipeline can actually produce from its real corpus.
    """

    chemical_name: str = Field(
        description="Chemical being classified (for audit/display only)"
    )
    nfpa_health: int = Field(
        ge=0,
        le=4,
        description="NFPA 704 health rating (0-4). Caller must supply; not extracted from SDS.",
    )
    nfpa_flammability: int = Field(
        ge=0,
        le=4,
        description="NFPA 704 flammability rating (0-4). Caller must supply; not extracted from SDS.",
    )
    nfpa_instability: int = Field(
        ge=0,
        le=4,
        description="NFPA 704 instability rating (0-4). Caller must supply; not extracted from SDS.",
    )
    ghs_code_count: int = Field(
        ge=0,
        description="Number of GHS hazard statement codes (e.g. H225 -> 1 code). Derivable from len(ProvenancedThreshold.hazard_statements).",
    )


class SeverityResponse(BaseModel):
    """Response for POST /classifier/severity.

    The classifier output is a severity band (LOW/MEDIUM/HIGH/CRITICAL) with a
    confidence score. This is NOT a safety verdict (SAFE/WARNING/UNKNOWN) -- it
    labels the hazard severity of the chemical for triage purposes, downstream
    of the deterministic safety-state machine.
    """

    chemical_name: str
    severity: str  # "LOW", "MEDIUM", "HIGH", or "CRITICAL"
    confidence: float  # model probability for the predicted class
    nfpa_health: int
    nfpa_flammability: int
    nfpa_instability: int
    ghs_code_count: int
    note: str  # explains that NFPA inputs are caller-supplied, not extracted


# ============================================================================
# Agent B — Open Query Orchestrator (M3, PR 3)
# ============================================================================


class OpenQueryRequest(BaseModel):
    """Request body for POST /query/open.

    Accepts natural language queries from safety officers, e.g.
    'Why did Zone B flag a warning?' or 'What are the storage limits for Toluene?'
    """

    query: str = Field(
        min_length=1, description="Open-ended natural language safety query"
    )


class OpenQueryResponse(BaseModel):
    """Response from POST /query/open.

    Returns the synthesized response coordinated by OpenQueryOrchestrator,
    along with the list of tools that were registered and available to the LLM.
    """

    query: str
    response: str
    tools_registered: list[str]
